<!--========= TERISI OTOMATIS =============-->
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right"></label>
                                <div class="col-12 col-sm-10 col-lg-8">
                                <!-- input nomor -->
                                <div class="form-row">
                                    <div class="col-xl-5 col-lg-5 col-md-12 col-sm-12 col-12 mb-2">
                                        <label for="validationCustom04">Tanggal Berangkat</label>
                                        <div class=" input-group date" id="" data-target-input="nearest">
                                            <input name="tgl_berangkat" type="date" class="form-control datetimepicker-input" data-target="#datetimepicker4"  />
                                        <!-- end input tgl kembali -->
                                        <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="far fa-calendar-alt"></i></div>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="col-xl-5 col-lg-5 col-md-12 col-sm-12 col-12 mb-2">
                                        <label for="validationCustom05">Tanggal Kembali</label>
                                        <div class=" input-group date" id="" data-target-input="nearest">
                                            <!-- input tgl kembali -->
                                            <input name="tgl_kembali" type="date" class="form-control datetimepicker-input" data-target="#datetimepicker41"  />
                                            <div class="input-group-append" data-target="#datetimepicker41" data-toggle="datetimepicker">
                                                <div class="input-group-text"><i class="far fa-calendar-alt"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right"></label>
                                <div class="col-12 col-sm-10 col-lg-8">
                                <div class="form-row">
                                    <div class="col-xl-2 col-lg-2 col-md-12 col-sm-12 col-12 mb-2">
                                        <label for="validationCustom05">Tujuan</label>
                                    </div>
                                    <div class="col-xl-7 col-lg-7 col-md-12 col-sm-12 col-12 mb-2">
                                        <input name="tujuan" type="text" class="form-control" readonly="" />
                                        </div>
                                    </div>
                                </div>
                                </div>
                            </div>